version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - config-vol:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env

volumes:
  config-vol:
